import math

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# 
# Answer: 4613732

def fib(n):
    return round((1 / math.sqrt(5)) * ((1 + math.sqrt(5)) / 2) ** n)

sum = 0
i = 1
while fib(i) <= 4000000:
    if fib(i) % 2 == 0:
        sum += fib(i)
    i += 1

print(sum)
